- name: Deploying Application to Kubernetes
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
  tasks:
    - name: Create Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        src: deployment.yaml
        namespace: "{{ namespace_name }}"

    - name: Expose application on NodePort
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        src: service.yaml
        namespace: "{{ namespace_name }}"
