- hosts: localhost
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
    copy:
      src: service.yaml
      dest: /root/
  - name: delete the previous of deployment
    command: kubectl delete -f /root/deployment.yaml
  - name: delete the previous of service
    command: kubectl delete -f /root/service.yaml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/deployment.yaml
  - name: Create a Service by reading the definition from a local file
    command: kubectl apply -f /root/service.yaml
