- hosts: localhost
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
    copy:
      src: service.yaml
      dest: /root/
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /root/deployment.yaml
    command: kubectl delete -f /root/service.yaml
  - name: Create a Deployment and Service by reading the definition from a local file
    command: kubectl apply -f /root/deployment.yaml
    command: kubectl apply -f /root/service.yaml
