- hosts: localhost
  tasks:
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f deployment.yaml
    command: kubectl delete -f service.yaml
  - name: Create a Deployment and Service by reading the definition from a local file
    command: kubectl apply -f deployment.yaml
    command: kubectl apply -f service.yaml
